objects = program1 program2
CC = g++                        # compiler to use
CXXFLAGS='-std=c++17'
INCLUDE="-I."

objects = complex main 
all: $
	$(CC) $(CXXFLAGS) $(INCLUDE) *.cpp -o main.x
	./main.x
